0_overview_pipeline_sirene_rne.md

1_Acquisition_SIRENE.md
1.1_Acquisition_SIRENE_stock_details.md
1.2_Acquisition_SIRENE_flux_details.md

2_Acquisition_RNE.md
2.1_Acquisition_RNE_stock_details.md
2.2_Acquisition_RNE_flux_details.md
2.3_RNE_database_details.md

3_ETL_SIRENE.md
3.1_ETL_tables_sirene_stock_details.md
3.2_ETL_tables_sirene_flux_details.md
3.3_ETL_integration_RNE_details.md
3.4_ETL_enrichissements_secondaires_details.md
3.5_ETL_validations_volumetrie_details.md
3.6_ETL_sortie_sirene_db_details.md
3.7_ETL_metadata_generation_details.md

4_Consommateurs.md
4.1_Elasticsearch_indexation_details.md
4.2_DataGouv_exports_details.md

5_Enrichissements_secondaires_overview.md
5.x_<dataset>_details.md
